### ISSUE TITLE
Exception thrown on application bootstrap

### ISSUE THREAD

**Issue by maheshambiga** [liu-dongyu/react-swiper#1]
Getting below exception,
\node_modules\swiper\dist\js\swiper.js:3627
            var ua = navigator.userAgent.toLowerCase();
                     ^

ReferenceError: navigator is not defined

**Comment by liu-dongyu** [comment]
Please file this with the [swiper](https://github.com/nolimits4web/swiper/) library. If it's react-swiper's problem， re-open this issue and show more info.
